---
title: "ManyFaces pilot ratings"
subtitle: "Compiling ratings by face"
format: 
  html:
    code-fold: true
    df-print: paged
    embed-resources: true
    fig-height: 5
    fig-width: 8
    toc: true
execute: 
  error: true
---

```{r}
#| message: false
library(tidyverse)
```

## Load data
```{r}
# Rating data
data_exp <- read_csv("data/manyfaces-pilot-exp_cleaned.csv",
                     show_col_types = FALSE)

exp_levels_neutral <- c("attractive", "trustworthy", "dominant", 
                        "memorable", "gender-typical")

exp_levels_emotion_int <- c("fear", "anger", "disgust", 
                            "happiness", "sadness", "surprise")

# Questionnaire data
data_qu <- read_csv("data/manyfaces-pilot-quest_cleaned.csv",
                    show_col_types = FALSE)

# Model data
data_model <- read_csv("data/manyfaces-pilot-models_cleaned.csv",
                       show_col_types = FALSE)

rainbow <- c("firebrick", "darkorange", "goldenrod", "darkgreen", "dodgerblue3", "darkorchid4")
```

## Standardised neutral ratings

```{r}
std_neutral <- data_exp |>
  filter(exp %in% exp_levels_neutral) |>
  mutate(dv = as.integer(dv),
         exp = factor(exp, exp_levels_neutral)) |> 
  separate_wider_delim(trial_name,
                       delim = "_",
                       names = c("lab_id", "model_id"),
                       too_many = "drop")
```

```{r}
std_neutral |>
  summarise(N = n(),
            mean_rating = mean(dv),
            .by = c("exp", "lab_id", "model_id")) |> 
  summarise(N = first(N),
            M = mean(mean_rating),
            SD = sd(mean_rating),
            .by = "exp") |> 
mutate(across(where(is.numeric) & !any_of("N"), ~ round(.x, 2)))
```

```{r}
std_neutral_means <- std_neutral |> 
  summarise(mean_rating = mean(dv),
            rater_N = n(),
            .by = c("exp", "lab_id", "model_id")) |> 
  pivot_wider(id_cols = c(lab_id, model_id),
              names_from = exp,
              #values_from = c(mean_rating, rater_N))
              values_from = mean_rating)
```


### Plots
```{r}
std_neutral |>
  ggplot(aes(x = dv, fill = exp)) +
  geom_histogram(binwidth = 1, show.legend = FALSE, color = "black") +
  facet_wrap(~exp, ncol = 3, axes = "all_x", drop = FALSE) +
  labs(title = "Standardised neutral ratings",
       x = "") +
  scale_x_continuous(breaks = 1:7) +
  scale_fill_manual(values = rainbow, drop = FALSE)
```

```{r}
# function to create heatmap visualisations
heatmap <- function(exp_id, label) {
  std_neutral |>
    filter(exp %in% !!exp_id) |>
    count(lab_id, model_id, dv) |>
    ggplot(aes(x = dv, y = model_id, fill = n)) +
    geom_tile() +
    facet_wrap(~lab_id) +
    scale_fill_viridis_c() +
    labs(x = label, y = NULL, 
         title = paste(label, "Ratings")) +
    theme(legend.position = "none", 
          axis.text.x = element_text(angle = 90))
}
```

#### Attractiveness

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("attractive", "Attractiveness")
```

#### Trustworthiness

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("trustworthy", "Trustworthiness")
```

#### Dominance

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("dominant", "Dominance")
```

#### Memorableness

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("memorable", "Memorableness")
 
```

#### Gender Typicality

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("gender-typical", "Gender Typicality")
```





## Unstandardised Neutral Ratings

```{r}
#| fig-height: 2.5
#| fig-width: 8
exp_labels <- c("attractive", "trustworthy", "dominant")
exp_levels <- paste(exp_labels, "(unstd)")

exp |>
  filter(exp_id %in% 1397:1399) |>
  mutate(dv = as.integer(dv), 
         exp = factor(exp, exp_levels, exp_labels)) |>
  ggplot(aes(x = dv, fill = exp)) +
  geom_histogram(binwidth = 1, show.legend = FALSE, color = "black") +
  facet_wrap(~exp, ncol = 5, drop = FALSE) +
  labs(title = "Unstandardised Neutral Ratings",
       x = "") +
  scale_x_continuous(breaks = 1:7) +
  scale_fill_manual(values = rainbow, drop = FALSE)
```

#### Attractiveness (Unstandardised)

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("attractive (unstd)", "Attractiveness (Unstandardised)")
```

#### Trustworthiness (Unstandardised)

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("trustworthy (unstd)", "Trustworthiness (Unstandardised)")
```

#### Dominance (Unstandardised)

```{r}
#| fig-height: 10
#| fig-width: 10

heatmap("dominant (unstd)", "Dominance (Unstandardised)")
```

## Emotion Ratings

```{r}
dv_levels <- c("anger", "disgust", "fear", 
                "happiness", "sadness", "surprise", "other")
emo_levels <- c("ang", "dis", "fea", "hap", "sad", "sur")
emo_labels <- paste(dv_levels[1:6], "faces")

exp |>
  filter(exp_id %in% c(1384, 1401:1405)) |>
  separate(trial_name, c("lab", "model", "type", "emo", "view")) |>
  mutate(dv = factor(dv, dv_levels),
         emo = factor(emo, emo_levels, emo_labels)) |>
  ggplot(aes(x = dv, fill = dv)) +
  geom_point(aes(x = x, colour = I(fill), fill = I(fill)), 
             data.frame(emo = factor(emo_levels, emo_levels, emo_labels),
                        x = 1:6,
                        fill = rainbow),
             size = 6.5, y = -60, shape = 18, show.legend = FALSE) +
  geom_bar(color = "transparent") +
  facet_wrap(~emo, axes = "all_x", drop = FALSE) +
  scale_x_discrete(labels = c("A", "D", "F", "H", "S", "U", "O")) +
  scale_fill_manual(values = c(rainbow, "grey"), drop = FALSE) +
  labs(title = "Emotion Ratings",
       x = "",
       fill = "Rated Emotion") +
  coord_cartesian(clip="off") +
  theme(axis.ticks.x = element_blank())
```

## Emotion Intensity Ratings

```{r}
exp_levels <- c("anger", "disgust", "fear", 
                "happiness", "sadness", "surprise")
               
exp |>
  filter(exp_id %in% 1385:1390) |>
  mutate(dv = as.integer(dv),
         exp = factor(exp, exp_levels)) |>
  ggplot(aes(x = dv, fill = exp)) +
  geom_histogram(binwidth = 1, show.legend = FALSE, color = "black") +
  facet_wrap(~exp, ncol = 3, axes = "all_x", drop = FALSE) +
  labs(title = "Emotion Intensity Ratings",
       x = "") +
  scale_fill_manual(values = rainbow, drop = FALSE) +
  scale_x_continuous(breaks = 1:7)
```

## Age Ratings

```{r}
dv_levels <- seq(20, 85, 5)
dv_labels <- paste(dv_levels-4, "-", dv_levels )
dv_labels[14] <- "81+"

exp |>
  filter(exp_id %in% 1400) |>
  mutate(dv = factor(dv, dv_levels, dv_labels)) |>
  ggplot(aes(x = dv)) +
  geom_bar(color = "black", fill = "white") +
  scale_x_discrete(drop = FALSE) +
  labs(title = "Age Ratings",
       x = "")
```

```{r}
# exp |>
#   filter(exp_id %in% 1400) |>
#   mutate(dv = as.numeric(dv) - 2.5) |>
#   summarise(age = mean(dv), age_sd = sd(dv), .by = trial_name)
```

```{r}
#| fig-height: 10
#| fig-width: 10

exp |>
  filter(exp_id %in% 1400) |>
  mutate(dv = factor(dv, dv_levels, dv_labels)) |>
  mutate(trial_name = gsub("_std_neu_0", "", trial_name)) |>
  separate(trial_name, c("lab", "id")) |>
  count(lab, id, dv) |>
  ggplot(aes(x = dv, y = id, fill = n)) +
  geom_tile() +
  facet_wrap(~lab) +
  scale_fill_viridis_c() +
  labs(x = "Age", y = NULL) +
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 90))
  
```

## Compile all ratings into one data file
```{r}
pilot_ratings <- data_model |> 
  left_join(std_neutral_means, by = c("lab_id", "model_id"))
```